### ISSUE TITLE
Override default constructor

### ISSUE THREAD

**Issue by valeriangalliat** [busbud/super-error#6]
I'd like to create an error with a custom constructor taking an object as parameter.

Currently [the default constructor is always called](https://github.com/busbud/super-error/blob/86fbe17c6aca81c10cb808db98d69c2e24988c42/index.js#L50), whether I define my custom constructor or no, resulting in the parameter object being merged in the error instance.

Example:

```js
var CustomError = SuperError.subclass('CustomError', function (obj) {
  this.bar = obj.foo
})

new CustomError({ foo: 42, ignoreMe: 1337 })

// Expected: { bar: 42 }
// Documented (and actual result): { foo: 42, ignoreMe: 1337, bar: 42 }
```

Is there a way to prevent the default constructor to be called (or call it with different arguments)?

BTW I believe it's really counter-intuitive to have the default constructor always called even if we define a custom constructor (even if documented), especially because one use case I'd expect for a custom constructor is to allow the end user to pass different kind of arguments than the super constructor (even if internally we can still `apply` the original constructor with adapted arguments).

A solution not involving any change in `super-error` could be to define some kind of static constructor like `CustomError.create(myObject)` calling the default constructor with the transformed arguments.

But I'd like other opinions on this behavior, and maybe discuss if we expect/want the default constructor to be always called or no.

Thanks!

**Comment by Chris911** [comment]
I like the idea of having a default minimalist constructor and a 2nd function that parses the args and sets the error message and properties only if a subclass constructor isn't passed.
